export const lang = {
    en: {
        // GENERAL UI
        language: 'PT-BR',
        bio:'<b>FULLSTACK</b> WEB DEVELOPER FOCUSED ON INTUITIVE AND <b>MINIMALIST</b> APLICATIONS',
        projects:'PROJECTS VIEWED',
        scroll:'SCROLL',
        // PROJECTS
        arariamaDesc:'',
        betterYouDesc:'',
        chatbotDesc:'',
        portfolio:'PORTFOLIO',
        portfolioDesc:'pt',
        speedLogDesc:'sp',
        sublimeDesc:'',
        talesTrailsDesc:'',
        ticTacToe:'TIC TAC TOE',
        ticTacToeDesc:'The classic tic-tac-toe game, with a <b>minimalist</b> and colorful design <b>aimed at children</b>',
        youtubeConverter:'YOUTUBE CONVERTER',
        youtubeConverterDesc:'yt',
        // FILTERS
        db:'Database',
        tools:'Tools',
        month2:'FEB',month4:'APR',month5:'MAY',month8:'AUG',month9:'SEP',month10:'OCT',month12:'DEC',
        // TAGS
        interactive:'Interactive',
        minigame:'Minigame',
        cart:'Cart',
        practical:"Practical",
        responsivity:'Responsive',
        colaboration:'Colaboration',
        logistics:'Logistics',
        permissions:'Permissions',
        showcase:'Showcase',
        vanilla:'Vanilla',
        mobile:'Mobile',
        ml:'Machine Learning',
        ai:'Artificial Intelligence',
        ux:'User Experience',
        ui:'User Interface',
    },
    pt: {
        language: 'EN-US',
        bio: 'DESENVOLVEDOR WEB <b>FULLSTACK</b> FOCADO EM APLICAÇÕES INTUITIVAS E <b>MINIMALISTAS</b>',
        projects:'PROJETOS VISTOS',
        scroll:'ROLE',

        arariamaDesc:'Comércio digital de livros usados',
        betterYouDesc:'',
        chatbotDesc:'',
        portfolio:'PORTIFÓLIO',
        portfolioDesc:'pt',
        speedLogDesc:'sp',
        sublimeDesc:'',
        talesTrailsDesc:'',
        ticTacToe:'JOGO DA VELHA',
        ticTacToeDesc:'O clássico jogo da velha, com um design <b>minimalista</b> voltado para o <b>público infantil</b>',
        youtubeConverter:"CONVERSOR DO YOUTUBE",
        youtubeConverterDesc:'YOUTUBE CONVERTER',

        db:'Banco de Dados',
        tools:'Ferramentas',
        month2:'FEV',month4:'ABR',month5:'MAI',month8:'AGO',month9:'SET',month10:'OUT',month12:'DEZ',
        
        interactive:'Interativo',
        minigame:'Minijogo',
        cart:'Carrinho',
        practical:"Prático",
        responsivity:'Responsivo',
        colaboration:'Colaboração',
        logistics:'Logística',
        permissions:'Permissões',
        showcase:'Amostragem',
        vanilla:'Puro',
        mobile:'Celular',
        ml:'Aprendizado Máquina',
        ai:'Inteligência Artificial',
        ux:'Experiência do Usuário',
        ui:'Interface do Usuário',
    }
};